//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Archivplan.UI.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dialog.Archivplan.UI.Web.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Abbrechen {
            get {
                return ResourceManager.GetString("Abbrechen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anrede.
        /// </summary>
        public static string Anrede {
            get {
                return ResourceManager.GetString("Anrede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivplan.
        /// </summary>
        public static string Archivplan {
            get {
                return ResourceManager.GetString("Archivplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufbewahrungsfrist.
        /// </summary>
        public static string Aufbewahrungsfrist {
            get {
                return ResourceManager.GetString("Aufbewahrungsfrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begriff.
        /// </summary>
        public static string Begriff {
            get {
                return ResourceManager.GetString("Begriff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellen.
        /// </summary>
        public static string Bestellen {
            get {
                return ResourceManager.GetString("Bestellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;a href=&apos;http://www.dialog.ch&apos;&gt;Dialog Verwaltungs-Data AG&lt;/a&gt; übernimmt keine Haftung für die Richtigkeit, Vollständigkeit und Aktualität.&lt;/p&gt;.
        /// </summary>
        public static string BestellenFooter {
            get {
                return ResourceManager.GetString("BestellenFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellung.
        /// </summary>
        public static string Bestellung {
            get {
                return ResourceManager.GetString("Bestellung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Der HRM2 Archivplan wurde vom &lt;a href=&apos;http://www.acf-fgv.ch&apos;&gt;Freiburger Gemeindeverband&lt;/a&gt; ausgearbeitet und wird Interessierten Verwaltungen kostenlos als Excel-Datei zur Verfügung gestellt.&lt;/p&gt;.
        /// </summary>
        public static string BestellungHeader {
            get {
                return ResourceManager.GetString("BestellungHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezeichnung.
        /// </summary>
        public static string Bezeichnung {
            get {
                return ResourceManager.GetString("Bezeichnung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string Deutsch {
            get {
                return ResourceManager.GetString("Deutsch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossierbildung.
        /// </summary>
        public static string Dossierbildung {
            get {
                return ResourceManager.GetString("Dossierbildung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMail.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich gesendet.
        /// </summary>
        public static string ErfolgreichGesendet {
            get {
                return ResourceManager.GetString("ErfolgreichGesendet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registratur-_und_Archivplan_Muster_FGV.xls.
        /// </summary>
        public static string ExcelDatei {
            get {
                return ResourceManager.GetString("ExcelDatei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der HRM2 Archivplan wurde vom &lt;a href=&apos;http://www.acf-fgv.ch&apos;&gt;Freiburger Gemeindeverband&lt;/a&gt; ausgearbeitet..
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Französisch.
        /// </summary>
        public static string Französisch {
            get {
                return ResourceManager.GetString("Französisch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frau.
        /// </summary>
        public static string Frau {
            get {
                return ResourceManager.GetString("Frau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haupttitel.
        /// </summary>
        public static string Haupttitel {
            get {
                return ResourceManager.GetString("Haupttitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herr.
        /// </summary>
        public static string Herr {
            get {
                return ResourceManager.GetString("Herr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis.
        /// </summary>
        public static string Hinweis {
            get {
                return ResourceManager.GetString("Hinweis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registratur.
        /// </summary>
        public static string Registratur {
            get {
                return ResourceManager.GetString("Registratur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registraturplan.
        /// </summary>
        public static string Registraturplan {
            get {
                return ResourceManager.GetString("Registraturplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untertitel.
        /// </summary>
        public static string Untertitel {
            get {
                return ResourceManager.GetString("Untertitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwaltungsname.
        /// </summary>
        public static string Verwaltungsname {
            get {
                return ResourceManager.GetString("Verwaltungsname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string Vorname {
            get {
                return ResourceManager.GetString("Vorname", resourceCulture);
            }
        }
    }
}
