//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antrag
    {
        public int AntragId { get; set; }
        public string FormData { get; set; }
        public bool Erledigt { get; set; }
    }
}
