//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datenbank
    {
        public Datenbank()
        {
            this.UserMappings = new HashSet<UserMapping>();
        }
    
        public int DatenbankId { get; set; }
        public int MandantId { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual Mandant Mandant { get; set; }
        public virtual ICollection<UserMapping> UserMappings { get; set; }
    }
}
