//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandant
    {
        public Mandant()
        {
            this.Datenbanks = new HashSet<Datenbank>();
        }
    
        public int MandantId { get; set; }
        public string Bezeichnung { get; set; }
        public string MandantUrl { get; set; }
        public string Module { get; set; }
    
        public virtual ICollection<Datenbank> Datenbanks { get; set; }
    }
}
