//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIDRequest
    {
        public string RequestId { get; set; }
        public int DatenbankId { get; set; }
        public bool Erfolgreich { get; set; }
        public string Handynummer { get; set; }
        public string Hash { get; set; }
        public bool IsAdmin { get; set; }
        public string ResponseMessage { get; set; }
        public string Shortname { get; set; }
        public string Status { get; set; }
        public string Token { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
