//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMapping
    {
        public string HandyNummer { get; set; }
        public int DatenbankId { get; set; }
        public string ShortName { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsGesperrt { get; set; }
        public string Vorname { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Demo { get; set; }
        public string Module { get; set; }
    
        public virtual Datenbank Datenbank { get; set; }
    }
}
