//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Archivplan.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBestellung
    {
        public int BestellungId { get; set; }
        public string Anrede { get; set; }
        public string Registraturplan { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public string Verwaltungsname { get; set; }
        public string EMail { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Status { get; set; }
    }
}
