//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbGESTraktandenKommmentar
    {
        public decimal TbGESTraktandenKommmentar_ID { get; set; }
        public decimal TbGESTraktanden_ID { get; set; }
        public Nullable<decimal> User_ID { get; set; }
        public Nullable<System.DateTime> StellungnahmeDatum { get; set; }
        public Nullable<decimal> TbGMXCodeStatus_ID { get; set; }
        public string Bemerkungen { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string Visum { get; set; }
        public Nullable<bool> Vertraulich { get; set; }
    }
}
