//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbGESSitzung
    {
        public TbGESSitzung()
        {
            this.TbGESSitzungTeilnehmers = new HashSet<TbGESSitzungTeilnehmer>();
            this.TbGESTraktandens = new HashSet<TbGESTraktanden>();
        }
    
        public decimal TbGESSitzung_id { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string Visum { get; set; }
        public Nullable<decimal> Status_id { get; set; }
        public string Bezeichnung { get; set; }
        public string KurzBezeichnung { get; set; }
        public decimal SitzungsArt_ID { get; set; }
        public decimal SitzungsOrt_ID { get; set; }
        public Nullable<System.DateTime> ZeitVon { get; set; }
        public Nullable<System.DateTime> ZeitBis { get; set; }
        public Nullable<decimal> Gremium_id { get; set; }
        public Nullable<System.DateTime> SitzungsDatum { get; set; }
        public string Jahr { get; set; }
        public decimal SitzungsNr { get; set; }
        public string Bemerkungen { get; set; }
        public string BemerkungenRTF { get; set; }
        public string FRMname { get; set; }
        public string ZusatzFeld1 { get; set; }
        public string ZusatzFeld2 { get; set; }
        public string ZusatzFeld3 { get; set; }
        public string ZusatzFeld4 { get; set; }
        public string ZusatzFeld5 { get; set; }
        public string ZusatzFeld6 { get; set; }
        public string ZusatzFeld7 { get; set; }
        public string ZusatzFeld8 { get; set; }
        public string ZusatzFeld9 { get; set; }
        public string ZusatzFeld10 { get; set; }
        public Nullable<decimal> ProtokollErsteSeiteNr { get; set; }
        public string ErfVisum { get; set; }
        public string WebFreigabe { get; set; }
    
        public virtual TbBHDGremium TbBHDGremium { get; set; }
        public virtual ICollection<TbGESSitzungTeilnehmer> TbGESSitzungTeilnehmers { get; set; }
        public virtual ICollection<TbGESTraktanden> TbGESTraktandens { get; set; }
    }
}
