//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbGESTraktanden
    {
        public decimal TbGESTraktanden_id { get; set; }
        public decimal TbGESSitzung_id { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string Visum { get; set; }
        public Nullable<int> Traktanden_NR { get; set; }
        public Nullable<decimal> TraktandenTyp_id { get; set; }
        public Nullable<decimal> TbGESGeschaeft_id { get; set; }
        public string PressMitteilung { get; set; }
        public string PressMitteilungRTF { get; set; }
        public string Titel { get; set; }
        public string TitelRTF { get; set; }
        public Nullable<int> Beschluss_NR { get; set; }
        public string FRMname { get; set; }
        public string Traktandum { get; set; }
        public string TraktandumRTF { get; set; }
        public Nullable<decimal> Offentlich { get; set; }
        public string Vermerk { get; set; }
        public Nullable<decimal> TbGMXCodeSachbearbeiter_ID { get; set; }
        public Nullable<System.DateTime> BeschlussDatum { get; set; }
        public Nullable<decimal> TbGMXCodeKompetenz_ID { get; set; }
        public Nullable<decimal> Betrag { get; set; }
        public string ErfVisum { get; set; }
    
        public virtual TbGESSitzung TbGESSitzung { get; set; }
    }
}
