//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMXCODEARTEN
    {
        public TBGMXCODEARTEN()
        {
            this.TBGMXCODEs = new HashSet<TBGMXCODE>();
        }
    
        public string CODEART { get; set; }
        public decimal TBGMXCODEARTEN_ID { get; set; }
        public string BEZ_FFTXT1 { get; set; }
        public string BEZ_FFTXT2 { get; set; }
        public string BEZ_FFTXT3 { get; set; }
        public string BEZ_FFTXT4 { get; set; }
        public string BEZ_FFNUM1 { get; set; }
        public string BEZ_FFNUM2 { get; set; }
        public string BEZ_FFNUM3 { get; set; }
        public string BEZ_FFNUM4 { get; set; }
        public Nullable<System.DateTime> ERFDATUM { get; set; }
        public Nullable<System.DateTime> MUTDATUM { get; set; }
        public string VISUM { get; set; }
        public string BEZEICHNUNG { get; set; }
        public string MODULS { get; set; }
        public Nullable<int> SCHUTZLEVEL { get; set; }
        public string DEFAULTFORM { get; set; }
        public string TbFeld { get; set; }
        public bool Mehrsprachig { get; set; }
    
        public virtual ICollection<TBGMXCODE> TBGMXCODEs { get; set; }
    }
}
