//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXArchivplan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArchivplan
    {
        public int RegPlanId { get; set; }
        public string RegPlanNr { get; set; }
        public int ParentId { get; set; }
        public string BezeichnungDE { get; set; }
        public string BezeichnungFR { get; set; }
        public string DossierbildungDE { get; set; }
        public string DossierbildungFR { get; set; }
        public string AufbewahrungsfristDE { get; set; }
        public string AufbewahrungsfristFR { get; set; }
        public string HaupttitelDE { get; set; }
        public string HaupttitelFR { get; set; }
        public string UntertitelDE { get; set; }
        public string UntertitelFR { get; set; }
        public string HinweisDE { get; set; }
        public string HinweisFR { get; set; }
    }
}
