//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BehoerdenloesungEntities : DbContext
    {
        public BehoerdenloesungEntities()
            : base("name=BehoerdenloesungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TbBHDGremium> TbBHDGremiums { get; set; }
        public virtual DbSet<TbGESGeschaeft> TbGESGeschaefts { get; set; }
        public virtual DbSet<TbGESSitzung> TbGESSitzungs { get; set; }
        public virtual DbSet<TbGESSitzungTeilnehmer> TbGESSitzungTeilnehmers { get; set; }
        public virtual DbSet<TbGESTraktanden> TbGESTraktandens { get; set; }
        public virtual DbSet<TbGESTraktandenBeilagen> TbGESTraktandenBeilagens { get; set; }
        public virtual DbSet<TbGESTraktandenKommmentar> TbGESTraktandenKommmentars { get; set; }
        public virtual DbSet<TBGMXCODE> TBGMXCODEs { get; set; }
        public virtual DbSet<TbGMXDatei> TbGMXDateis { get; set; }
        public virtual DbSet<TbGesTraktandenRegistratur> TbGesTraktandenRegistraturs { get; set; }
        public virtual DbSet<TbREGgruppe> TbREGgruppes { get; set; }
        public virtual DbSet<TbSysUSR> TbSysUSRs { get; set; }
        public virtual DbSet<vwGMXDateiMaxVersion> vwGMXDateiMaxVersions { get; set; }
        public virtual DbSet<TBADRPERSON> TBADRPERSONs { get; set; }
        public virtual DbSet<TbGESDatenSatzBerechtigungSetup> TbGESDatenSatzBerechtigungSetups { get; set; }
    }
}
