//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbSysUSR
    {
        public int ID { get; set; }
        public string InsUser { get; set; }
        public Nullable<System.DateTime> InsTime { get; set; }
        public string ModUser { get; set; }
        public Nullable<System.DateTime> ModTime { get; set; }
        public string Shortname { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<short> Active { get; set; }
        public Nullable<short> Admin { get; set; }
        public Nullable<int> CLT_ID { get; set; }
        public string Loginname { get; set; }
        public string PhoneDirect { get; set; }
        public string PhoneGeneral { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public Nullable<int> Abteilung_ID { get; set; }
        public string Abteilung { get; set; }
        public string Stelle { get; set; }
        public string Bereich { get; set; }
        public string Bemerkung { get; set; }
    }
}
