//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGMXDateiMaxVersion
    {
        public decimal ReferenzID { get; set; }
        public string ReferenzModul { get; set; }
        public string ReferenzMaske { get; set; }
        public string ReferenzSection { get; set; }
        public string DateiName { get; set; }
        public Nullable<int> Version { get; set; }
    }
}
