//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbAFGAufgabe
    {
        public decimal TbAFGAufgabe_id { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string Visum { get; set; }
        public string Betreff { get; set; }
        public Nullable<System.DateTime> Beginn { get; set; }
        public Nullable<System.DateTime> Faellig { get; set; }
        public Nullable<decimal> AufgabeStatus_ID { get; set; }
        public Nullable<decimal> AufgabePrioritaet_ID { get; set; }
        public Nullable<int> Erledigt { get; set; }
        public Nullable<System.DateTime> Erinnerung { get; set; }
        public string Beschreibung { get; set; }
        public string BeschreibungRTF { get; set; }
        public Nullable<decimal> TbGESGeschaeft_id { get; set; }
        public Nullable<decimal> AufgabeEigner_Gremiumid { get; set; }
        public Nullable<decimal> AufgabeEigner_Personid { get; set; }
        public Nullable<decimal> AuftragGeber_Gremiumid { get; set; }
        public Nullable<decimal> AuftragGeber_Personid { get; set; }
        public string FRMName { get; set; }
        public Nullable<decimal> Investitionen { get; set; }
        public Nullable<decimal> Voranschlag { get; set; }
        public Nullable<decimal> TbAFGAufgabeGruppe_ID { get; set; }
        public Nullable<decimal> TbAFGRecurrence_ID { get; set; }
        public string ErfVisum { get; set; }
    }
}
