//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbBHDInstitution
    {
        public TbBHDInstitution()
        {
            this.TbBHDGremiums = new HashSet<TbBHDGremium>();
        }
    
        public decimal TbBHDInstitution_id { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string Visum { get; set; }
        public Nullable<decimal> Mandant_id { get; set; }
        public string KurzBezeichnung { get; set; }
        public string Bezeichnung { get; set; }
        public string Bemerkungen { get; set; }
        public string Sortierung { get; set; }
        public Nullable<System.DateTime> AktivAbDatum { get; set; }
        public Nullable<System.DateTime> AktivBisDatum { get; set; }
        public string FRMname { get; set; }
        public string BemerkungenRTF { get; set; }
    
        public virtual ICollection<TbBHDGremium> TbBHDGremiums { get; set; }
        public virtual TbBHDMandant TbBHDMandant { get; set; }
    }
}
