//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbBHDGremium
    {
        public TbBHDGremium()
        {
            this.TbGESGeschaefts = new HashSet<TbGESGeschaeft>();
            this.TbGESSitzungs = new HashSet<TbGESSitzung>();
            this.TbBHDFunktions = new HashSet<TbBHDFunktion>();
        }
    
        public decimal TbBHDGremium_id { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string Visum { get; set; }
        public decimal Institution_id { get; set; }
        public Nullable<decimal> Abteilung_id { get; set; }
        public string KurzBezeichnung { get; set; }
        public string Bezeichnung { get; set; }
        public string Bemerkungen { get; set; }
        public string Sortierung { get; set; }
        public Nullable<System.DateTime> AktivAbDatum { get; set; }
        public Nullable<System.DateTime> AktivBisDatum { get; set; }
        public Nullable<System.DateTime> GruendungDatum { get; set; }
        public Nullable<System.DateTime> AbschlussDatum { get; set; }
        public string FRMname { get; set; }
        public string BemerkungenRTF { get; set; }
        public string Kommission { get; set; }
        public Nullable<decimal> amtsdauer { get; set; }
        public Nullable<decimal> amtsperioden { get; set; }
        public string DruckTitel { get; set; }
        public string Regplan { get; set; }
        public Nullable<decimal> Gremiumart { get; set; }
    
        public virtual ICollection<TbGESGeschaeft> TbGESGeschaefts { get; set; }
        public virtual ICollection<TbGESSitzung> TbGESSitzungs { get; set; }
        public virtual TbBHDInstitution TbBHDInstitution { get; set; }
        public virtual ICollection<TbBHDFunktion> TbBHDFunktions { get; set; }
    }
}
