//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbBHDMandant
    {
        public TbBHDMandant()
        {
            this.TbBHDInstitutions = new HashSet<TbBHDInstitution>();
        }
    
        public decimal TbBHDMandant_id { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string Visum { get; set; }
        public string KurzBezeichnung { get; set; }
        public string Bezeichnung { get; set; }
        public string Bemerkungen { get; set; }
        public string Sortierung { get; set; }
        public string FRMname { get; set; }
        public string BemerkungenRTF { get; set; }
    
        public virtual ICollection<TbBHDInstitution> TbBHDInstitutions { get; set; }
    }
}
