//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbBHDMitglied
    {
        public decimal TbBHDMitglied_id { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string Visum { get; set; }
        public decimal TbBHDFunktion_id { get; set; }
        public Nullable<decimal> Person_id { get; set; }
        public Nullable<decimal> Wahlvoraussetzung_id { get; set; }
        public Nullable<decimal> Partei_id { get; set; }
        public Nullable<System.DateTime> Wahldatum { get; set; }
        public Nullable<System.DateTime> Vereidigungsdatum { get; set; }
        public Nullable<System.DateTime> EntrittDatum { get; set; }
        public Nullable<System.DateTime> AustrittDatum { get; set; }
        public Nullable<System.DateTime> AmtBeginnDatum { get; set; }
        public Nullable<System.DateTime> AmtEndeDatum { get; set; }
        public string bemerkungen { get; set; }
        public string FRMname { get; set; }
        public string bemerkungenRTF { get; set; }
        public string Protokollfuehrung { get; set; }
        public string Sitzungsleitung { get; set; }
        public string KontoAngaben { get; set; }
        public string FunktionBezeichnung { get; set; }
        public Nullable<decimal> Sitzanspruch { get; set; }
        public string RessortBezeichnung { get; set; }
        public string Protokollfuehrung2 { get; set; }
        public string HomePageBild { get; set; }
        public Nullable<decimal> TbSYSUsr_ID { get; set; }
    
        public virtual TBADRPERSON TBADRPERSON { get; set; }
        public virtual TbBHDFunktion TbBHDFunktion { get; set; }
    }
}
