//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbGESGeschaeftBemerkung
    {
        public decimal TbGESGeschaeftBemerkung_ID { get; set; }
        public decimal TbGESGeschaeft_ID { get; set; }
        public Nullable<decimal> Sachbearbeiter_ID { get; set; }
        public Nullable<System.DateTime> BemerkungDatum { get; set; }
        public Nullable<decimal> TbGMXCodeArt_ID { get; set; }
        public string Bemerkungen { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string ErfVisum { get; set; }
        public string MutVisum { get; set; }
    }
}
