//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbGESGeschaeft
    {
        public decimal TbGESGeschaeft_id { get; set; }
        public Nullable<decimal> TbRegGruppe_Id { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string Visum { get; set; }
        public Nullable<decimal> GesStatus_id { get; set; }
        public string Titel { get; set; }
        public string TitelRTF { get; set; }
        public Nullable<System.DateTime> BeginnDatum { get; set; }
        public Nullable<System.DateTime> EndeDatum { get; set; }
        public Nullable<decimal> Eigner_id { get; set; }
        public Nullable<decimal> EignerSachbearbeiterID { get; set; }
        public Nullable<decimal> AuftragGeber_id { get; set; }
        public Nullable<decimal> AuftragGeberSachbearbeiterID { get; set; }
        public Nullable<decimal> TbGMXStichWorte_Id { get; set; }
        public Nullable<System.DateTime> FaelligkeitDatum { get; set; }
        public string Bemerkungen { get; set; }
        public string BemerkungenRTF { get; set; }
        public string FRMname { get; set; }
        public Nullable<decimal> Aufbewahr_Id { get; set; }
        public Nullable<decimal> GeschaeftsTyp { get; set; }
        public Nullable<decimal> Offentlich { get; set; }
        public string BemerkungenIntern { get; set; }
        public string BemerkungenInternRTF { get; set; }
        public string ErfVisum { get; set; }
        public Nullable<decimal> TbADRPerson_ID { get; set; }
        public string WebFreigabe { get; set; }
    
        public virtual TbBHDGremium TbBHDGremium { get; set; }
        public virtual TbREGgruppe TbREGgruppe { get; set; }
    }
}
