//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbGESSitzungTeilnehmer
    {
        public decimal TbGESSitzungTeilnehmer_id { get; set; }
        public decimal TbGESSitzung_id { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string Visum { get; set; }
        public Nullable<decimal> TbBHDMitglied_id { get; set; }
        public string Protokollfuehrung { get; set; }
        public string Sitzungsleitung { get; set; }
        public string FRMname { get; set; }
        public string Anwesend { get; set; }
        public Nullable<decimal> Abwesenheit { get; set; }
        public Nullable<System.DateTime> Zeitvon { get; set; }
        public Nullable<System.DateTime> Zeitbis { get; set; }
        public Nullable<decimal> Menge { get; set; }
        public Nullable<decimal> Tarif_ID { get; set; }
        public string Pauschal { get; set; }
        public Nullable<decimal> Ansatz { get; set; }
        public Nullable<decimal> Betrag { get; set; }
        public Nullable<decimal> Spesen { get; set; }
        public Nullable<System.DateTime> Abrechnung { get; set; }
        public Nullable<decimal> KM { get; set; }
        public Nullable<decimal> KMBetrag { get; set; }
        public string Bemerkungen { get; set; }
        public string FunktionBezeichnung { get; set; }
        public Nullable<decimal> TBADRPerson_ID { get; set; }
        public string Protokollfuehrung2 { get; set; }
    
        public virtual TbGESSitzung TbGESSitzung { get; set; }
    }
}
