//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbGESVerantwortlichkeit
    {
        public decimal TbGESVerantwortlichkeit_id { get; set; }
        public Nullable<decimal> TbGESGeschaeft_id { get; set; }
        public Nullable<decimal> VerantwortlichkeitTyp { get; set; }
        public Nullable<decimal> Rolle_id { get; set; }
        public Nullable<decimal> TbBHDGremium_id { get; set; }
        public Nullable<decimal> Sachbearbeiter_id { get; set; }
        public string SourceFormName { get; set; }
        public Nullable<decimal> TbAFGAufgabe_id { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string Visum { get; set; }
    }
}
