//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbGMXGlobal
    {
        public decimal TBGMXGLOBAL_ID { get; set; }
        public string CODEKEY { get; set; }
        public string INHALT { get; set; }
        public string BEMERKUNGEN { get; set; }
        public Nullable<System.DateTime> ERFDATUM { get; set; }
        public Nullable<System.DateTime> MUTDATUM { get; set; }
        public string VISUM { get; set; }
        public Nullable<int> Mandant { get; set; }
        public bool System { get; set; }
    }
}
