//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGMXCODE
    {
        public decimal TBGMXCODE_ID { get; set; }
        public string CODEKEY { get; set; }
        public string BEZ { get; set; }
        public string VIS { get; set; }
        public bool DEFAULTWERT { get; set; }
        public string SORT { get; set; }
        public bool SYSTEMCODE { get; set; }
        public bool AKTIVCODE { get; set; }
        public string FFTXT1 { get; set; }
        public string FFTXT2 { get; set; }
        public string FFTXT3 { get; set; }
        public string FFTXT4 { get; set; }
        public Nullable<float> FFNUM1 { get; set; }
        public Nullable<float> FFNUM2 { get; set; }
        public Nullable<float> FFNUM3 { get; set; }
        public Nullable<float> FFNUM4 { get; set; }
        public Nullable<System.DateTime> ERFDATUM { get; set; }
        public Nullable<System.DateTime> MUTDATUM { get; set; }
        public string VISUM { get; set; }
        public string CODEART { get; set; }
        public string KURZ_BEZ { get; set; }
        public Nullable<System.DateTime> GUELTIGAB { get; set; }
        public Nullable<System.DateTime> GUELTIGBIS { get; set; }
        public string Sprach_CD { get; set; }
        public string CODEBEM { get; set; }
    }
}
