//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbGMXDatei
    {
        public decimal TbGMXDatei_id { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string Visum { get; set; }
        public decimal ReferenzID { get; set; }
        public string ReferenzModul { get; set; }
        public string ReferenzMaske { get; set; }
        public string ReferenzSection { get; set; }
        public string DateiName { get; set; }
        public string DateiTyp { get; set; }
        public Nullable<decimal> Kategorie { get; set; }
        public string Titel { get; set; }
        public Nullable<int> Version { get; set; }
        public string Beschreibung { get; set; }
        public string CheckOut { get; set; }
        public string Deleted { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<decimal> ART { get; set; }
        public Nullable<System.DateTime> ErstelltDatum { get; set; }
        public Nullable<System.DateTime> EingangDatum { get; set; }
        public Nullable<System.DateTime> AusgangDatum { get; set; }
        public Nullable<decimal> TbRegGruppe_Id { get; set; }
        public Nullable<decimal> TbGMXDateiFolder_Id { get; set; }
        public Nullable<decimal> EigenschaftenVisum_ID { get; set; }
        public Nullable<decimal> TbADRPerson_ID { get; set; }
        public Nullable<decimal> AufbewahrungsFrist { get; set; }
        public Nullable<System.DateTime> AufbewahrungBis { get; set; }
        public string PhysischeAblage { get; set; }
        public Nullable<long> DateiGroesse { get; set; }
        public string PhysischeAblageBezeichnung { get; set; }
        public byte[] Datei { get; set; }
        public string IsIndexiert { get; set; }
        public byte[] Datei_image { get; set; }
    }
}
