//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog.Behoerdenloesung.Sitzungen.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbREGgruppe
    {
        public TbREGgruppe()
        {
            this.TbGESGeschaefts = new HashSet<TbGESGeschaeft>();
        }
    
        public decimal TbREGgruppe_id { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string Visum { get; set; }
        public string Nummer { get; set; }
        public Nullable<decimal> HauptGruppe_id { get; set; }
        public string Sortierung { get; set; }
        public string Name { get; set; }
        public string keyword { get; set; }
        public Nullable<decimal> TBBHDMandant_id { get; set; }
        public string verweise { get; set; }
        public string Bemerkungen { get; set; }
        public Nullable<int> GroupLevel { get; set; }
        public Nullable<decimal> Aufbewahr_id { get; set; }
        public string Aktiv { get; set; }
        public string FRMname { get; set; }
        public string BemerkungenRTF { get; set; }
        public Nullable<decimal> GeschaeftEigner_ID { get; set; }
        public Nullable<decimal> AuftragGeber_ID { get; set; }
        public string Gliederung { get; set; }
        public Nullable<decimal> GeschaeftTyp_ID { get; set; }
    
        public virtual ICollection<TbGESGeschaeft> TbGESGeschaefts { get; set; }
    }
}
